services: 
  # Servidor Web Apache + PHP
  web:
    build: .
    container_name: pedro_web
    ports: 
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - pedro_network
    restart: unless-stopped

  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: pedro_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pedro_db
      MYSQL_USER: pedro_user
      MYSQL_PASSWORD: pedro123
    ports:
      - "3306:3306"
    volumes:
      - pedro_data:/var/lib/mysql
    networks:
      - pedro_network
    restart: unless-stopped

  # phpMyAdmin para gerenciamento do banco de dados
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pedro_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - pedro_network
    restart: unless-stopped

# Volumes para persistência de dados
volumes:
  pedro_data:

# Rede interna para comunicação entre os containers
networks:
  pedro_network:
    driver: bridge

