services:
  web:
    build: .
    container_name: startup_web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - startup_network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: startup_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: startup_db
      MYSQL_USER: startup_user
      MYSQL_PASSWORD: startup123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - startup_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: startup_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - startup_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  startup_network:
    driver: bridge
